// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuRFrs1xl1fUxHEKoNA0PMKnwaqQIiWBM',
    appId: '1:141158839857:web:1237dbec358cd491db4710',
    messagingSenderId: '141158839857',
    projectId: 'akinbyk-f655c',
    authDomain: 'akinbyk-f655c.firebaseapp.com',
    storageBucket: 'akinbyk-f655c.firebasestorage.app',
    measurementId: 'G-9D8SE2MML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwpgeEAlxJnpzUCLeSnEaTmxLBhs5VVw',
    appId: '1:141158839857:android:a47b9534e5ca5e78db4710',
    messagingSenderId: '141158839857',
    projectId: 'akinbyk-f655c',
    storageBucket: 'akinbyk-f655c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLMDFce2a791z_NlSZp_lb-znztyhuQmY',
    appId: '1:141158839857:ios:266ff445323e180edb4710',
    messagingSenderId: '141158839857',
    projectId: 'akinbyk-f655c',
    storageBucket: 'akinbyk-f655c.firebasestorage.app',
    iosBundleId: 'com.example.kisilerUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLMDFce2a791z_NlSZp_lb-znztyhuQmY',
    appId: '1:141158839857:ios:266ff445323e180edb4710',
    messagingSenderId: '141158839857',
    projectId: 'akinbyk-f655c',
    storageBucket: 'akinbyk-f655c.firebasestorage.app',
    iosBundleId: 'com.example.kisilerUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuRFrs1xl1fUxHEKoNA0PMKnwaqQIiWBM',
    appId: '1:141158839857:web:e706210c01028d39db4710',
    messagingSenderId: '141158839857',
    projectId: 'akinbyk-f655c',
    authDomain: 'akinbyk-f655c.firebaseapp.com',
    storageBucket: 'akinbyk-f655c.firebasestorage.app',
    measurementId: 'G-CM6MFRL2R1',
  );
}
